### ISSUE TITLE
Get-G2DObjectFromPolicyRulesFile skips registry values for the same key

### ISSUE THREAD

**Issue by hoffimar** [nyanhp/GpoToDsc#6]
I just tried to convert the MS Security Baseline Policy from the Security Compliance Toolkit (for Win10 1809, filename is MSFT-Win10-v1809-RS5-FINAL.PolicyRules) to DSC and found that a lot of registry values are not in the output of the above function.
Looking at the source code at https://github.com/nyanhp/GpoToDsc/blob/dev/GpoToDsc/functions/Get-G2DObjectFromPolicyRulesFile.ps1 it looks like line 130ff and 73ff filter for an already read entry with the same registry **key**, regardless of the registry **value**. Is there any reason for this? I would have expected that the values under 1 key are independent and would be added. Of course one would have to handle potential deletions of keys.

**Comment by nyanhp** [comment]
Good catch. The Key/ValueName pair needs to be unique, not the key only.
